services:
  db:
    container_name: student_planner_db
    image: postgres:16.4-alpine
    hostname: postgreshost
    ports:
      - '5432:5432'
    user: postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=hunter2
      - POSTGRES_DB=planner
    volumes:
      - planner-db:/var/lib/postgresql/data
    healthcheck:
      test: [ 'CMD-SHELL', 'pg_isready -U postgres -d planner' ]
      interval: 10s
      timeout: 5s
      retries: 3

  pgadmin:
    container_name: student_planner_pgadmin
    depends_on:
      db:
        condition: service_healthy
    image: dpage/pgadmin4
    ports:
      - '3001:80'
    environment:
      - PGADMIN_DEFAULT_EMAIL=your@email.com
      - PGADMIN_DEFAULT_PASSWORD=hunter2
    user: root
    volumes:
      - planner-db:/var/lib/postgresql/data

  backend:
    container_name: student_planner_backend
    depends_on:
      db:
        condition: service_healthy
    build:
      context: student-planner-backend
    ports:
      - '8080:8080'
      - '5005:5005'
    healthcheck:
      test: "curl --fail --silent localhost:8080/actuator/health | grep UP || exit 1"
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 40s

volumes:
  planner-db:
    driver: local