services:
  db:
    container_name: student_planner_db
    image: postgres:16.4-alpine
    hostname: postgreshost
    user: postgres
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=planner
    volumes:
      - planner-db:/var/lib/postgresql/data
    healthcheck:
      test: [ 'CMD-SHELL', 'pg_isready -U $POSTGRES_USER -d planner' ]
      interval: 10s
      timeout: 5s
      retries: 3
    restart: always

  backend:
    container_name: student_planner_backend
    depends_on:
      db:
        condition: service_healthy
    build:
      context: student-planner-backend
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - ADMIN_USERNAME=${ADMIN_USERNAME}
      - ADMIN_PASSWORD=${ADMIN_PASSWORD}
    healthcheck:
      test: "curl --fail --silent localhost:8080/actuator/health | grep UP || exit 1"
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 40s
    restart: always

  frontend:
    container_name: student_planner_frontend
    depends_on:
      backend:
        condition: service_healthy
    build:
      context: student-planner-frontend
    ports:
      - '8080:3000'
    restart: always


volumes:
  planner-db:
    driver: local