name: Build and upload image

on:
  push:
    branches:
      - "main"

env:
  REGISTRY: docker.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build-push:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: build and push image
        run:
          docker login -u lichtb -p ${{ secrets.DOCKER_HUB_TOKEN }}
          docker build --build-arg POSTGRES_USER=${{ secrets.POSTGRES_USER }} --build-arg POSTGRES_PASSWORD=${{ secrets.POSTGRES_PASSWORD }} --build-arg ADMIN_USERNAME=${{ secrets.ADMIN_USERNAME }} --build-arg ADMIN_PASSWORD=${{ secrets.ADMIN_PASSWORD }} -t lichtb/student-planner:latest .